services:
  - type: web
    name: ledgerflow-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "4000"
      - key: DATABASE_URL
        fromDatabase:
          name: ledgerflow-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: ledgerflow-redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_CALLBACK_URL
        sync: false

  - type: keyvalue
    name: ledgerflow-redis
    plan: free
    ipAllowList: []
    maxmemoryPolicy: noeviction

databases:
  - name: ledgerflow-db
    plan: free
    databaseName: saas_assinaturas
    user: saas
